package io.github.gokulhk.spacesaver.buildlogic

import io.gitlab.arturbosch.detekt.Detekt
import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension
import kotlinx.kover.gradle.plugin.dsl.KoverReportFiltersConfig
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies

/**
 * Applies detekt and Kover to a module. Both hook into `check`, so `./gradlew check`
 * runs static analysis and coverage verification for every module.
 */
internal fun Project.configureQuality() {
    pluginManager.apply(libs.pluginId("detekt"))
    pluginManager.apply(libs.pluginId("kover"))
    configureDetekt()
    extensions.configure<KoverProjectExtension> {
        reports.filters { excludeGeneratedAndUiEntryPoints() }
    }
}

private fun Project.configureDetekt() {
    extensions.configure<DetektExtension> {
        buildUponDefaultConfig = true
        parallel = true
        config.setFrom(rootProject.file("config/detekt/detekt.yml"))
        // Analyze every source set (main, test, androidTest, debug...), not only main and test.
        source.setFrom(files("src"))
    }
    dependencies {
        add("detektPlugins", libs.library("compose-rules-detekt"))
    }
    tasks.withType(Detekt::class.java).configureEach {
        jvmTarget = jvmTargetVersion.toString()
        reports.html.required.set(true)
        reports.sarif.required.set(true)
        reports.xml.required.set(false)
        reports.txt.required.set(false)
        reports.md.required.set(false)
    }
}

/**
 * Excludes code that unit tests cannot meaningfully cover: code generated by Hilt, Dagger,
 * Room, and the Compose compiler, plus Composable functions and previews, which are covered
 * by Compose UI and screenshot tests instead.
 */
internal fun KoverReportFiltersConfig.excludeGeneratedAndUiEntryPoints() {
    excludes {
        annotatedBy(
            "androidx.compose.runtime.Composable",
            "androidx.compose.ui.tooling.preview.Preview",
            "dagger.Module",
            "dagger.hilt.android.AndroidEntryPoint",
            "dagger.hilt.android.HiltAndroidApp",
            "dagger.internal.DaggerGenerated",
            "javax.annotation.processing.Generated",
        )
        classes(
            "*.BuildConfig",
            "*.R",
            "*.R$*",
            "*.ComposableSingletons*",
            "*_Factory",
            "*_Factory$*",
            "*_HiltModules*",
            "*_MembersInjector",
            "*_Impl",
            "*_Impl$*",
            "Hilt_*",
            "*.Hilt_*",
            "dagger.hilt.internal.*",
            "hilt_aggregated_deps.*",
        )
    }
}
